/**
 * FlowDesk Business Plan AI — core AI feature (serverless function)
 *
 * Takes 6 plain-English answers about a business idea and returns a
 * structured one-page business plan (7 sections) plus a 12-month
 * revenue/cost forecast — generated by a single Claude Haiku call.
 *
 * SETUP (one manual step before this goes live):
 *   1. Get an Anthropic API key from https://console.anthropic.com
 *   2. In Vercel project settings, add an environment variable:
 *        ANTHROPIC_API_KEY = sk-ant-...
 *   3. Redeploy. That's it.
 */

const SYSTEM_PROMPT = `You are a startup advisor who writes clear, realistic one-page business plans for first-time founders. Given six short answers from a founder describing their business idea, you produce exactly one JSON object (no prose, no markdown fences) with this shape:

{
  "sections": [
    { "h": "The Problem", "t": "string, 2-4 sentences" },
    { "h": "The Solution", "t": "string, 2-4 sentences" },
    { "h": "Target Market", "t": "string, 2-4 sentences" },
    { "h": "Business Model", "t": "string, 2-4 sentences" },
    { "h": "Go-To-Market", "t": "string, 2-4 sentences" },
    { "h": "Costs & Timeline", "t": "string, 2-4 sentences" },
    { "h": "12-Month Milestone", "t": "string, 2-4 sentences" }
  ],
  "forecast": [
    { "month": "Month 1", "revenue": number, "costs": number },
    ... exactly 12 entries, "Month 1" through "Month 12" ...
  ]
}

Rules:
- Always return valid JSON and nothing else.
- Ground every section in the founder's actual answers.
- The forecast must be realistic and internally consistent.
- revenue and costs must be plain integers.`;

// Simple per-IP rate limiter (resets on cold start — 20 req/min per IP)
const _rateMap = new Map();
function isRateLimited(ip) {
  const now = Date.now(), window = 60000, limit = 20;
  const e = _rateMap.get(ip) || { n: 0, reset: now + window };
  if (now > e.reset) { e.n = 0; e.reset = now + window; }
  e.n++; _rateMap.set(ip, e);
  return e.n > limit;
}

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' });

  const clientIp = (req.headers['x-forwarded-for'] || req.socket?.remoteAddress || '').split(',')[0].trim();
  if (isRateLimited(clientIp)) return res.status(429).json({ error: 'rate_limited', message: 'Too many requests — please wait a minute.' });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return res.status(503).json({ error: 'not_configured', message: 'ANTHROPIC_API_KEY is not set.' });
  }

  let answers = [];
  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    answers = Array.isArray(body && body.answers) ? body.answers : [];
    answers = answers.map(a => (a || '').toString().trim().slice(0, 500)).slice(0, 6);
  } catch (e) {
    return res.status(400).json({ error: 'bad_request' });
  }
  if (!answers[0]) return res.status(400).json({ error: 'missing_answers' });

  const labels = ['The business idea','Target customer','Revenue / pricing model','Estimated startup cost','Timeline to launch','12-month definition of success'];
  const briefing = labels.map((l, i) => `${i + 1}. ${l}: ${answers[i] || '(not provided)'}`).join('\n');

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 2200,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: `Here is the founder's intake:\n\n${briefing}\n\nReturn the JSON object now.` }]
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      return res.status(502).json({ error: 'upstream_error', message: errText.slice(0, 300) });
    }

    const data = await response.json();
    const raw = (data.content && data.content[0] && data.content[0].text) || '';

    let parsed;
    try {
      const cleaned = raw.trim().replace(/^```(json)?/i, '').replace(/```$/, '').trim();
      parsed = JSON.parse(cleaned);
    } catch (e) {
      return res.status(502).json({ error: 'parse_error' });
    }

    if (!Array.isArray(parsed.sections) || !Array.isArray(parsed.forecast)) {
      return res.status(502).json({ error: 'shape_error' });
    }

    const sections = parsed.sections.slice(0, 7).map(s => ({ h: String(s.h || '').slice(0, 60), t: String(s.t || '').slice(0, 800) }));
    const forecast = parsed.forecast.slice(0, 12).map((r, i) => ({ month: String(r.month || `Month ${i + 1}`).slice(0, 20), revenue: Math.max(0, Math.round(Number(r.revenue) || 0)), costs: Math.max(0, Math.round(Number(r.costs) || 0)) }));

    return res.status(200).json({ sections, forecast });
  } catch (err) {
    return res.status(500).json({ error: 'server_error', message: String(err && err.message || err) });
  }
};
